### 1. 创建一个长度为10的一维全为0的ndarray对象，然后让第5个元素等于1

In [2]:
import numpy as np
a=np.zeros(10)
print((a))
a[4]=1
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 2. 创建一个元素为从10到49的ndarray对象
2.1 包含20个元素  
2.2 每隔3取值一个元素

In [3]:
#2 从10到49的ndarray对象
a=np.arange(10,50)
print(a)
#2.1 包含20个元素的ndarray对象
b=np.linspace(10,49,20)
print(b)
#2.2 每隔3取值一个元素
c=np.arange(10,50,3)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[10.         12.05263158 14.10526316 16.15789474 18.21052632 20.26315789
 22.31578947 24.36842105 26.42105263 28.47368421 30.52631579 32.57894737
 34.63157895 36.68421053 38.73684211 40.78947368 42.84210526 44.89473684
 46.94736842 49.        ]
[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


### 3. 将2中最后一个ndarray翻转

In [4]:
reverse=c[::-1]
print(reverse)

[49 46 43 40 37 34 31 28 25 22 19 16 13 10]


### 4. 使用np.random.random创建一个10*10的ndarray对象，并打印出最大最小元素

In [5]:
d=np.random.random((10,10))
print(d)
print(d.max())
print(d.min())

[[0.18750685 0.62997927 0.52819438 0.08693416 0.17699513 0.18104799
  0.07578256 0.04021077 0.70897813 0.71507062]
 [0.52721567 0.10839312 0.73758203 0.54414073 0.30126433 0.58802211
  0.17197552 0.61870629 0.1379751  0.47708376]
 [0.98178427 0.58511323 0.54060769 0.43446256 0.97578273 0.77768754
  0.17775347 0.54767835 0.24316148 0.03914381]
 [0.13472126 0.77017496 0.27901589 0.90512053 0.93757427 0.67535261
  0.47710309 0.27404675 0.99583006 0.27477413]
 [0.99755159 0.13838633 0.38865605 0.9952087  0.81969447 0.09337563
  0.99102657 0.03121017 0.19861525 0.60311688]
 [0.63880827 0.09872687 0.73990033 0.26476105 0.79288757 0.30393757
  0.57187853 0.81481288 0.07491763 0.11819979]
 [0.62342509 0.86369249 0.90152662 0.89399893 0.5254379  0.93878258
  0.72440415 0.52257065 0.97155641 0.49263964]
 [0.27537217 0.40851522 0.24841934 0.20330682 0.40964708 0.7668909
  0.97862396 0.05795159 0.49511575 0.88571396]
 [0.13417426 0.35294794 0.54873599 0.58989248 0.38049922 0.84500358
  0.86119016 

### 5. 创建一个10*10的ndarray对象，且矩阵边界全为1，里面全为0

In [6]:
e=np.zeros((10,10))
e[[0,9]]=1
e[:,[0,9]]=1
print(e)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 6. 创建一个每一行都是从0到4的5*5矩阵

In [7]:
f=np.array([0,1,2,3,4]*5).reshape(5,5)
print(f)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 7. 创建一个长度为10的随机数组并将最大值替换为0

In [8]:
g=np.random.randint(0,100,10)
print(g)
gmax=g.max()
gmaxwhere=g==gmax #g==max returns an ndarray containing true, false, ...(only one "true" when it indexes the max value.)
g[gmaxwhere]=0
print(g)

[89 73 15 20 49 10 96 66 96 10]
[89 73 15 20 49 10  0 66  0 10]


### 8. 生成长度为10的随机数组m
8.1 运行print(t.argsort())  
8.2 运行t.sort()  
比较两个排序命令的区别

In [9]:
m=np.random.randint(0,100,10)
print(m)
#8.1
print(m.argsort())
#8.2
m.sort()
print(m)

#区别：print(t.argsort())将数组按从小到大排列，并按照对应的索引值输出；sort()在原数组上进行从小到大的重新排序。

[36 78 32 47 49  1 90 63  7 45]
[5 8 2 0 9 3 4 7 1 6]
[ 1  7 32 36 45 47 49 63 78 90]


### 9. 给定一个4维矩阵，如何得到最后两维的和？
可使用np.random.randint(0,10,(3,3,3,3))生成0到9范围内的随机整数矩阵

In [10]:
h=np.random.randint(0,10,(3,3,3,3))
j=h.sum(axis=(-1,-2))
print(j)

[[43 40 42]
 [46 47 40]
 [30 54 32]]


### 10. 给定数组[1, 2, 3, 4, 5]，如何得到在这个数组的每个元素之间插入3个0后的新数组？

In [11]:
o=np.arange(1,6)
p=np.zeros(17,dtype=np.int8)
p[::4]=o
print(p)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


### 11. 给定一个二维矩阵，如何交换其中两行的元素？

In [12]:
q=np.random.randint(0,100,(3,3))
print(q)
print(q[[1,0,2]])

[[25  3 98]
 [12 10 28]
 [57 61 93]]
[[12 10 28]
 [25  3 98]
 [57 61 93]]


### 12. 创建一个5 \* 3 随机矩阵和一个3 \* 2随机矩阵，求矩阵积

In [13]:
r=np.random.randint(0,10,(5,3))
s=np.random.randint(0,10,(3,2))
product=np.dot(r,s)
print(r)
print(s)
print(product)

[[6 1 4]
 [4 0 0]
 [9 7 5]
 [0 4 5]
 [7 4 8]]
[[6 9]
 [4 6]
 [4 9]]
[[ 56  96]
 [ 24  36]
 [102 168]
 [ 36  69]
 [ 90 159]]


### 13. 生成一个5 \*5 的0到10之间的随机整数矩阵，矩阵的每一行的元素都减去该行的平均值

In [14]:
u=np.random.randint(0,11,(5,5))
print(u)
average=u.mean(axis=1).reshape(5,1)
print(average)
u=u-average 
print(u)

[[ 0  1  1  9  4]
 [ 8  3  3  9  1]
 [ 4  5  4  4  2]
 [ 1  7 10  7  0]
 [ 5  6  8  1  8]]
[[3. ]
 [4.8]
 [3.8]
 [5. ]
 [5.6]]
[[-3.  -2.  -2.   6.   1. ]
 [ 3.2 -1.8 -1.8  4.2 -3.8]
 [ 0.2  1.2  0.2  0.2 -1.8]
 [-4.   2.   5.   2.  -5. ]
 [-0.6  0.4  2.4 -4.6  2.4]]


### 14. 生成如下矩阵：
[[0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 [0 1 0 1 0 1 0 1]  
 [1 0 1 0 1 0 1 0]  
 14.1 要求使用np.zeros创建8*8的矩阵  
 14.2 np.fromfunction创建

In [15]:
#14.1
v=np.zeros((8,8),dtype=np.int8)
v[::2,1::2]=1
v[1::2,::2]=1
print(v)

#14.2
def fun(x,y):
    return((x+y)%2)
w=np.fromfunction(fun,(8,8),dtype=np.int8)
print(w)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 15、正则化一个5\*5随机矩阵  
【正则的概念：假设a是矩阵中的一个元素，max/min分别是矩阵元素的最大最小值，则正则化后a = (a - min)/(max - min)】

In [10]:
z=np.random.randint(0,100,size=(5,5))
print(z)
zmin=z.min()
zmax=z.max()
z=(z-zmin)/(zmax-zmin)
print(z)

[[ 6 67 73 11 50]
 [34 27 11  6 64]
 [22 51 96 65 83]
 [96 55 56 81 74]
 [73 43 11 15 73]]
[[0.         0.67777778 0.74444444 0.05555556 0.48888889]
 [0.31111111 0.23333333 0.05555556 0.         0.64444444]
 [0.17777778 0.5        1.         0.65555556 0.85555556]
 [1.         0.54444444 0.55555556 0.83333333 0.75555556]
 [0.74444444 0.41111111 0.05555556 0.1        0.74444444]]
